test:
 msg: hello kimhab from rb-publisher
server:
 port: 8081
eureka:
 client:
  serviceUrl: 
   defaultZone: http://localhost:8761/eureka
spring:
 rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
   

 
